---
title: "Homework 3"
author: "Ashleigh Bynum"
date: "November 24, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r EDA }
#Read the crash CSV file
library(tidyverse)
library(plyr)
library(readr)


crash <- read.csv("C:/Users/bynum/Desktop/Rockhurst/BIA 6301 - Applied Data Mining/Assignment/Assignment 2/crash.csv", stringsAsFactors = TRUE)


#Bar graph of Genders in our dataset
ggplot(data = crash) +
  geom_bar()

#separate alcohol vs. non-alcohol crashes
crashalcohol = crash %>% filter(crash$Alcohol.Results > 0.00)
crashnoalcohol = crash %>% filter(crash$Alcohol.Results == 0.00)



#Histogram of Make to female blood alcohol level
ggplot(data = crashalcohol) +
  geom_histogram(mapping = aes(x = crashalcohol$Alcohol.Results))+
  facet_wrap(~crashalcohol$Gender, nrow = 2)+
  xlab("Alcohol Level")+
  ylab("Count")
  
crashalcohol %>% count(crashalcohol$Gender)
crashnoalcohol %>% count(crashnoalcohol$Gender)


#Plotting Age vs. Alcohol Levels
ggplot(data = crashalcohol) +
  geom_point(mapping = aes(y = crashalcohol$Alcohol.Results, x = crashalcohol$Age), color = "Purple") +
  geom_smooth(mapping = aes(y = crashalcohol$Alcohol.Results, x = crashalcohol$Age), color = "Black")+
  xlab("Age") +
  ylab("Alcohol Level")+
  facet_grid(.~ Region)+
  scale_x_continuous("Age") +
  scale_y_continuous("Alcohol Level")

#Gender to Region
genderdf = crash %>% filter(crash$Gender == "Female" | crash$Gender == "Male")

ggplot(data = genderdf) +
  geom_bar(mapping = aes(x = genderdf$Gender)) +
  facet_grid(.~ Region)


#Drug involvement by State


drugdf = crash %>% filter(crash$Drug.Involvement == "Yes")


count(drugdf$Drug.Involvement, drugdf$State)

ggplot(data = drugdf) +
  geom_bar(mapping = aes(x = drugdf$Drug.Involvement)) +
  facet_grid(.~ Region)


lapply(crash, class)
```

 

```{r pressure, echo=FALSE}

crash_clean <- read.csv("C:/Users/abynum/Desktop/Rockhurst/BIA 6301 - Applied Data Mining/Assignment/Assignment 2/crash_raw.csv", stringsAsFactors = FALSE, as.is = TRUE)


library(clustMixType)

#Check for missing values
sapply(crash_clean, function(x) sum(is.na(x)))


 #Convert Binary data to factors
crash_clean [, 2:75] = lapply(crash_clean[,2:75], factor)


#Convert Continuous to Numeric
crash_clean$Fatalities = as.numeric(crash_clean$Fatalities)
crash_clean$Age = as.numeric(crash_clean$Age)
crash_clean$Alcohol_recorded = as.numeric(crash_clean$Alcohol_recorded)
crash_clean$crash_year = as.factor(crash_clean$crash_year)
crash_clean$crash_month = as.factor(crash_clean$crash_month)
crash_clean$crash_day = as.factor(crash_clean$crash_day)
crash_clean$crash_weekday = as.factor(crash_clean$crash_weekday)



#Elbow Method for finding the optimal number of clusters
set.seed(123)
# Compute and plot wss for k = 2 to k = 15.

crash_clean = na.omit(crash_clean)

table(is.na(crash_clean)) 

mydata <- as.data.frame(unclass(crash_clean))
summary(mydata)
dim(mydata)
dist(mydata)


rapply( mydata, f=function(x) ifelse(is.nan(x),0,x), how="replace" )

dist(mydata[,2])
wss =  (nrow(myDataClean[2:75])-1)*sum(apply(myDataClean[2:75],2,var))
  for (i in 2:15) wss[i] <- sum(kmeans(myDataClean[2:75],
                                  centers=i)$withinss)

wss
plot(1:15, wss, type="b", xlab="Number of Clusters",
     ylab="Within groups sum of squares")

lapply(mydata, class)

#K=7 Clusters
set.seed(2345)
k7 = kproto(crash_clean, k = 7, nstart = 25 )

k7$centers


#K=10 Clusters
set.seed(2345)
k10 = kproto(crash, k = 10)

k10$size
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
